### ISSUE TITLE
ESLint giving config error. ALE gets mad.

### ISSUE THREAD

**Issue by jwmann** [w0rp/ale#1075]
ALE throws an eslint config error
ALEDetails shows the message below

```
/Users/jwmann/work//app/.eslintrc:
        Configuration for rule "object-curly-spacing" is invalid:
        Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"always"').   
```

Here's the actual JSON I'm using for config:
```
{
  "env": {
    "es6": true,
    "browser": true,
    "node": true
  },
  "rules": {
    "curly": 0,
    "comma-dangle": [2, "never"],
    "comma-spacing": 0,
    "eqeqeq": [2, "allow-null"],
    "key-spacing": 0,
    "no-underscore-dangle": 0,
    "no-unused-expressions": 0,
    "no-shadow": 0,
    "no-shadow-restricted-names": 0,
    "no-extend-native": 0,
    "no-var": 2,
    "new-cap": 0,
    "quotes": 0,
    "semi-spacing": 0,
    "space-unary-ops": 0,
    "space-infix-ops": 0,
    "consistent-return": 0,
    "strict": 0,
    "object-curly-spacing" : ["always"],
    "react/jsx-uses-vars": [2]
  },
  "parser": "babel-eslint",
  "plugins": [
    "react",
    "eslint-plugin-react"
  ],
  "ecmaFeatures": {
    "arrowFunctions": true,
    "jsx": true
  }
}
```

I'm pretty sure I'm passing `object-curly-spacing` properly. Am I missing something?
Thanks.

ALEInfo
-------
```
 
 Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo', 'csslint', 'stylelint']
  Enabled Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo', 'stylelint']
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_jscs_executable = 'jscs'
let g:ale_javascript_jscs_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {'jsx': 'css'}
let g:ale_linters = {'jsx': ['stylelint', 'eslint']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) flow
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(executable check - failure) stylelint
(finished - exit code 1) ['/bin/bash', '-c', '''/Users/jwmann/work//app/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/jwmann/work//app/components/ReportTable.jsx'' < ''/var/folders/c4/_nphxbwd6_s4l7ksmc6l47lm0000gn/T/vBPOuav/6/ReportTable.jsx''']

<<<OUTPUT STARTS>>>
/Users/jwmann/work//app/.eslintrc:
^IConfiguration for rule "object-curly-spacing" is invalid:
^ISeverity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"always"').

Error: /Users/jwmann/work//app/.eslintrc:
^IConfiguration for rule "object-curly-spacing" is invalid:
^ISeverity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"always"').

    at validateRuleOptions (/Users/jwmann/work//app/node_modules/eslint/lib/config/config-validator.js:109:15)
    at Object.keys.forEach.id (/Users/jwmann/work//app/node_modules/eslint/lib/config/config-validator.js:156:13)
    at Array.forEach (<anonymous>)
    at Object.validate (/Users/jwmann/work//app/node_modules/eslint/lib/config/config-validator.js:155:35)
    at Object.load (/Users/jwmann/work//app/node_modules/eslint/lib/config/config-file.js:559:19)
    at loadConfig (/Users/jwmann/work//app/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/jwmann/work//app/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/jwmann/work//app/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/jwmann/work//app/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/jwmann/work//app/node_modules/eslint/lib/cli-engine.js:754:26)
<<<OUTPUT ENDS>>>

(executable check - failure) flow
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(executable check - failure) stylelint
(finished - exit code 1) ['/bin/bash', '-c', '''/Users/jwmann/work//app/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/jwmann/work//app/components/ReportTable.jsx'' < ''/var/folders/c4/_nphxbwd6_s4l7ksmc6l47lm0000gn/T/vBPOuav/7/ReportTable.jsx''']

<<<OUTPUT STARTS>>>
/Users/jwmann/work//app/.eslintrc:
^IConfiguration for rule "object-curly-spacing" is invalid:
^ISeverity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"always"').

Error: /Users/jwmann/work//app/.eslintrc:
^IConfiguration for rule "object-curly-spacing" is invalid:
^ISeverity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"always"').

    at validateRuleOptions (/Users/jwmann/work//app/node_modules/eslint/lib/config/config-validator.js:109:15)
    at Object.keys.forEach.id (/Users/jwmann/work//app/node_modules/eslint/lib/config/config-validator.js:156:13)
    at Array.forEach (<anonymous>)
    at Object.validate (/Users/jwmann/work//app/node_modules/eslint/lib/config/config-validator.js:155:35)
    at Object.load (/Users/jwmann/work//app/node_modules/eslint/lib/config/config-file.js:559:19)
    at loadConfig (/Users/jwmann/work//app/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/jwmann/work//app/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/jwmann/work//app/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/jwmann/work//app/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/jwmann/work//app/node_modules/eslint/lib/cli-engine.js:754:26)
<<<OUTPUT ENDS>>>

(executable check - failure) flow
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(executable check - failure) stylelint
```

**Comment by jwmann** [comment]
Just realized you have to add a severity rating to the rule array.
```
"object-curly-spacing" : [1, "always"]
```
Fixes it. Also has nothing to do with ALE.

**Comment by w0rp** [comment]
Ah, I was about to say that. ALE was just reporting was ESLint said, and the option wasn't set correctly.
