### ISSUE TITLE
Parse line numbers for ember-template-lint

### ISSUE THREAD

**Issue by jsit** [w0rp/ale#1240]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 28 2017 06:16:39)
macOS version

Operating System: MacOS 10.13.2

## What went wrong

ember-template-lint doesn't put the sign on the correct line number in SignColumn; the sign is just on line 1.

## Reproducing the bug

Steps for repeating the bug:

1. Write a handlebars file with an error or warning in it
2. See that the error/warning sign is only on line 1

**Comment by w0rp** [comment]
This was only happening for fatal errors. Now if the line and columns are included, they will be parsed.

**Comment by jsit** [comment]
I'm still seeing the issue with this error output:

```json
   {
      "fatal": true,
      "moduleId": "xxxxxxx",
      "message": "Parse error on line 8:\n...{t \"Xxxxx.Yyyyy\"}}\"      width=\"24\"\n-----------------------^\nExpecting 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'CLOSE'",
      "source": "Error: Parse error on line 8:\n...{t \"Xxxxx.Yyyyy\"}}\"      width=\"24\"\n-----------------------^\nExpecting 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'CLOSE'\n    at Parser.parseError (/usr/local/lib/node_modules/ember-template-lint/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:268:19)\n    at Parser.parse (/usr/local/lib/node_modules/ember-template-lint/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:337:30)\n    at HandlebarsEnvironment.parse (/usr/local/lib/node_modules/ember-template-lint/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:43)\n    at preprocess (/usr/local/lib/node_modules/ember-template-lint/node_modules/@glimmer/syntax/dist/commonjs/es5/lib/parser/tokenizer-event-handlers.js:335:60)\n    at precompile (/usr/local/lib/node_modules/ember-template-lint/node_modules/@glimmer/compiler/dist/commonjs/es5/lib/compiler.js:44:38)\n    at Linter.verify (/usr/local/lib/node_modules/ember-template-lint/lib/index.js:113:7)\n    at lintFile (/usr/local/lib/node_modules/ember-template-lint/bin/ember-template-lint.js:36:17)\n    at getRelativeFilePaths.reduce (/usr/local/lib/node_modules/ember-template-lint/bin/ember-template-lint.js:68:22)\n    at Array.reduce (<anonymous>)\n    at run (/usr/local/lib/node_modules/ember-template-lint/bin/ember-template-lint.js:66:39)",
      "severity": 2
    }
```

**Comment by w0rp** [comment]
I or someone else can have a look at that later. The error doesn't include the line number in the JSON, but does in the text, for some reason.

**Comment by w0rp** [comment]
Please include the output of `:ALEInfo` in future so others can look at the output you received.
