### ISSUE TITLE
Stylelint configuration issue?

### ISSUE THREAD

**Issue by xavierartot** [w0rp/ale#1544]
## Information

**version**
vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  3 2017 02:46:51)
macOS version

Operating System: WHAT OS WERE YOU USING?
Mac OS
### :ALEInfo

PASTE OUTPUT OF `:ALEInfo` HERE. YOU CAN TRY `:ALEInfoToClipboard`.
 Current Filetype: css
Available Linters: ['csslint', 'stylelint']
  Enabled Linters: ['csslint', 'stylelint']
 Linter Variables:

let g:ale_css_stylelint_executable = 'stylelint'
let g:ale_css_stylelint_options = ''
let g:ale_css_stylelint_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = '❧ Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning 📣'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['eslint']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '⚠️'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '💡'
let g:ale_statusline_format = ['error', 'warning %d', '']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) csslint
(finished - exit code 78) ['bash', '-c', 'stylelint  --stdin-filename ''/Applications/MAMP/htdocs/nanodegree/react/reactnd-contacts-complete/src/index.css'' < ''/var/folders/bj/13769vcn17bc6ldhg2b3htdr0000gn/T/vjWJwqz/38/index.css''']

<<<OUTPUT STARTS>>>
Error: Undefined rule selector-no-combinator
    at module.exports (/usr/local/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:304:13)
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:297:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:89:14)
    at <anonymous>
<<<OUTPUT ENDS>>>

(executable check - failure) csslint
(started) ['bash', '-c', 'stylelint  --stdin-filename ''/Applications/MAMP/htdocs/nanodegree/react/reactnd-contacts-complete/src/index.css'' < ''/var/folders/bj/13769vcn17bc6ldhg2b3htdr0000gn/T/vjWJwqz/39/index.css''']
(executable check - failure) csslint
(started) ['bash', '-c', 'stylelint  --stdin-filename ''/Applications/MAMP/htdocs/nanodegree/react/reactnd-contacts-complete/src/index.css'' < ''/var/folders/bj/13769vcn17bc6ldhg2b3htdr0000gn/T/vjWJwqz/40/index.css''']
(executable check - failure) csslint
(finished - exit code 78) ['bash', '-c', 'stylelint  --stdin-filename ''/Applications/MAMP/htdocs/nanodegree/react/reactnd-contacts-complete/src/index.css'' < ''/var/folders/bj/13769vcn17bc6ldhg2b3htdr0000gn/T/vjWJwqz/41/index.css''']

<<<OUTPUT STARTS>>>
Error: Undefined rule selector-no-combinator
    at module.exports (/usr/local/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:304:13)
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:297:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:89:14)
    at <anonymous>
<<<OUTPUT ENDS>>>

(executable check - failure) csslint
(finished - exit code 78) ['bash', '-c', 'stylelint  --stdin-filename ''/Applications/MAMP/htdocs/nanodegree/react/reactnd-contacts-complete/src/index.css'' < ''/var/folders/bj/13769vcn17bc6ldhg2b3htdr0000gn/T/vjWJwqz/42/index.css''']

<<<OUTPUT STARTS>>>
Error: Undefined rule selector-no-combinator
    at module.exports (/usr/local/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:304:13)
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:297:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:89:14)
    at <anonymous>
<<<OUTPUT ENDS>>>

(executable check - failure) csslint
(finished - exit code 78) ['bash', '-c', 'stylelint  --stdin-filename ''/Applications/MAMP/htdocs/nanodegree/react/reactnd-contacts-complete/src/index.css'' < ''/var/folders/bj/13769vcn17bc6ldhg2b3htdr0000gn/T/vjWJwqz/43/index.css''']

<<<OUTPUT STARTS>>>
Error: Undefined rule selector-no-id
    at module.exports (/usr/local/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:304:13)
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:297:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:89:14)
    at <anonymous>
<<<OUTPUT ENDS>>>
 Current Filetype: css
Available Linters: ['csslint', 'stylelint']
  Enabled Linters: ['csslint', 'stylelint']
 Linter Variables:

let g:ale_css_stylelint_executable = 'stylelint'
let g:ale_css_stylelint_options = ''
let g:ale_css_stylelint_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = '❧ Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning 📣'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['eslint']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '⚠️'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '💡'
let g:ale_statusline_format = ['error', 'warning %d', '']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) csslint
(finished - exit code 78) ['bash', '-c', 'stylelint  --stdin-filename ''/Applications/MAMP/htdocs/nanodegree/react/reactnd-contacts-complete/src/index.css'' < ''/var/folders/bj/13769vcn17bc6ldhg2b3htdr0000gn/T/vjWJwqz/38/index.css''']

<<<OUTPUT STARTS>>>
Error: Undefined rule selector-no-combinator
    at module.exports (/usr/local/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:304:13)
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:297:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:89:14)
    at <anonymous>
<<<OUTPUT ENDS>>>

(executable check - failure) csslint
(started) ['bash', '-c', 'stylelint  --stdin-filename ''/Applications/MAMP/htdocs/nanodegree/react/reactnd-contacts-complete/src/index.css'' < ''/var/folders/bj/13769vcn17bc6ldhg2b3htdr0000gn/T/vjWJwqz/39/index.css''']
(executable check - failure) csslint
(started) ['bash', '-c', 'stylelint  --stdin-filename ''/Applications/MAMP/htdocs/nanodegree/react/reactnd-contacts-complete/src/index.css'' < ''/var/folders/bj/13769vcn17bc6ldhg2b3htdr0000gn/T/vjWJwqz/40/index.css''']
(executable check - failure) csslint
(finished - exit code 78) ['bash', '-c', 'stylelint  --stdin-filename ''/Applications/MAMP/htdocs/nanodegree/react/reactnd-contacts-complete/src/index.css'' < ''/var/folders/bj/13769vcn17bc6ldhg2b3htdr0000gn/T/vjWJwqz/41/index.css''']

<<<OUTPUT STARTS>>>
Error: Undefined rule selector-no-combinator
    at module.exports (/usr/local/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:304:13)
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:297:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:89:14)
    at <anonymous>
<<<OUTPUT ENDS>>>

(executable check - failure) csslint
(finished - exit code 78) ['bash', '-c', 'stylelint  --stdin-filename ''/Applications/MAMP/htdocs/nanodegree/react/reactnd-contacts-complete/src/index.css'' < ''/var/folders/bj/13769vcn17bc6ldhg2b3htdr0000gn/T/vjWJwqz/42/index.css''']

<<<OUTPUT STARTS>>>
Error: Undefined rule selector-no-combinator
    at module.exports (/usr/local/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:304:13)
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:297:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:89:14)
    at <anonymous>
<<<OUTPUT ENDS>>>

(executable check - failure) csslint
(finished - exit code 78) ['bash', '-c', 'stylelint  --stdin-filename ''/Applications/MAMP/htdocs/nanodegree/react/reactnd-contacts-complete/src/index.css'' < ''/var/folders/bj/13769vcn17bc6ldhg2b3htdr0000gn/T/vjWJwqz/43/index.css''']

<<<OUTPUT STARTS>>>
Error: Undefined rule selector-no-id
    at module.exports (/usr/local/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:304:13)
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:297:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:89:14)
    at <anonymous>
<<<OUTPUT ENDS>>>

## What went wrong

WRITE WHAT WENT WRONG HERE.
I installed stylelint with npm i stylelint -g
I added a .stylelintrc
```
{
	"rules": {
		"color-hex-case": "lower",
		"color-hex-length": "short",
		"comment-empty-line-before": "always",
		"selector-no-id": true,
		"string-quotes": "double",
		"selector-no-type": true,
		"selector-no-universal": true,
		"selector-no-vendor-prefix": true
	}
}

```
here my .vimrc:
```
"LINT
"React  https://jaxbot.me/articles/setting-up-vim-for-react-js-jsx-02-03-2015
let g:jsx_ext_required = 0 " Allow JSX in normal JS files
let g:ale_statusline_format = ['error', 'warning %d', '']
"g:syntastic_javascript_checkers = ['eslint']
let g:ale_linters = {
\  'javascript': ['stylelint', 'eslint'],
\  'css': ['stylelint', 'eslint'],
\}
let g:ale_sign_error = '⚠️' "Less aggressive than the default '>>'
let g:ale_sign_warning = '💡'
"let g:ale_echo_msg_warning_str = 'Warning 📣'
"let g:ale_echo_msg_error_str = '❧ Error'
let g:ale_lint_on_enter = 0 " Less distracting when opening a new file
"run eslint in the backgrount with AsyncRun
autocmd BufWritePost *.js AsyncRun -post=checktime eslint --fix %
"autocmd BufWritePost *.js AsyncRun -post=checktime ./node_modules/.bin/eslint --fix %
"~/node_modules/eslint/bin/eslint.js
"
highlight clear ALEErrorSign
highlight clear ALEWarningSign
```
I have this error
```
Error: Undefined rule selector-no-id
    at module.exports (/usr/local/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:304:13)
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:297:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:89:14)
    at <anonymous>
```

**Comment by chaucerbao** [comment]
This looks like a problem with your Stylelint configuration.

You're using a rule, `selector-no-id`, that has been deprecated in v8.0.0 ([Changelog](https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md))
