### ISSUE TITLE
Flake8 not working when it has Chinese character

### ISSUE THREAD

**Issue by sevenboom** [w0rp/ale#800]
thers is the ALEinfo:
```
 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'pylint']
  Enabled Linters: ['flake8']
 Linter Variables:

let g:ale_python_flake8_executable = 'python3'
let g:ale_python_flake8_options = '-m flake8'
let g:ale_python_flake8_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = '✹ Error'
let g:ale_echo_msg_format = '[#%linter%#] %s [%severity%]'
let g:ale_echo_msg_warning_str = '⚠ Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['flake8']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '✘'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '！'
let g:ale_statusline_format = ['E•%d', 'W•%d', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 0) 'cmd /c python3 -m flake8 --version'
(finished - exit code 1) 'cmd /c python3 -m flake8 --stdin-display-name ***\www\handlers.py - < C:\Users\***\AppData\Local\Temp\VIACBE6.tmp\handlers.py'

<<<OUTPUT STARTS>>>
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\flake8-3.3.0-py3.6.egg\flake8\checker.py", line 471, in run_ast_checks
  File "C:\Python36\lib\site-packages\flake8-3.3.0-py3.6.egg\flake8\processor.py", line 211, in build_ast
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcaf' in position 270: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\lib\site-packages\flake8-3.3.0-py3.6.egg\flake8\__main__.py", line 4, in <module>
  File "C:\Python36\lib\site-packages\flake8-3.3.0-py3.6.egg\flake8\main\cli.py", line 16, in main
  File "C:\Python36\lib\site-packages\flake8-3.3.0-py3.6.egg\flake8\main\application.py", line 328, in run
  File "C:\Python36\lib\site-packages\flake8-3.3.0-py3.6.egg\flake8\main\application.py", line 316, in _run
  File "C:\Python36\lib\site-packages\flake8-3.3.0-py3.6.egg\flake8\main\application.py", line 246, in run_checks
  File "C:\Python36\lib\site-packages\flake8-3.3.0-py3.6.egg\flake8\checker.py", line 319, in run
  File "C:\Python36\lib\site-packages\flake8-3.3.0-py3.6.egg\flake8\checker.py", line 303, in run_serial
  File "C:\Python36\lib\site-packages\flake8-3.3.0-py3.6.egg\flake8\checker.py", line 573, in run_checks
  File "C:\Python36\lib\site-packages\flake8-3.3.0-py3.6.egg\flake8\checker.py", line 474, in run_ast_checks
  File "C:\Python36\lib\site-packages\flake8-3.3.0-py3.6.egg\flake8\checker.py", line 441, in _extract_syntax_information
TypeError: '>' not supported between instances of 'str' and 'int'
<<<OUTPUT ENDS>>>
```

It will work when change the Chinese character to English character

**Comment by w0rp** [comment]
This isn't a bug in ALE or flake8. You need to declare the encoding at the top of your file, and you need to configure the encoding in your editor appropriately. See here: https://docs.python.org/3/howto/unicode.html#python-s-unicode-support

**Comment by sevenboom** [comment]
but I had declare the encoding at the top of  file with 'utf-8', jusk like:
`# -*- coding: utf-8 -*- `
and I check the file encode with Notepad++ , the soft turn out the file encoded with 'utf-8 with out BOM'
and in my .vimrc  I set the file encoding in utf-8:
`set encoding=utf-8`                        
`set fileencoding=utf-8 `
but it still always report the error

**Comment by sevenboom** [comment]
Is it the reason that I used it in gvim on Windows

**Comment by w0rp** [comment]
Have a look through Google for `'\udcaf`'. One of the characters in your file isn't a valid UTF-8 character.

**Comment by sevenboom** [comment]
you can new a file with one line:
' print('你好吗‘)'
you will have the problem
it trouble me so many times , I can't have any way to solve It...

**Comment by sevenboom** [comment]
you can new a file with one line:
`print('你好吗‘)`
you will have the problem
it trouble me so many times , I can't have any way to solve It...

**Comment by sevenboom** [comment]
you can new a file with one line:
`print('你好吗')`
you will have the problem
it trouble me so many times , I can't have any way to solve It...
help me, please

**Comment by w0rp** [comment]
Make sure you create files with the correct encoding, and the correct characters. This is a Python issue, not an ALE issue.
