### ISSUE TITLE
ALE working but standardjs linter not.

### ISSUE THREAD

**Issue by german1608** [w0rp/ale#868]
I recently installed ALE via pathogen and I don't know why my `standard` linter doesn't work.
I used the `g:ale_linters` option to specify `standard` as my linter for javacript. But It just doesn't work.

If I dont' set that variable, all linters are enabled but the only one that works is `jshint`. 
Here is the output of :ALEInfo
```
Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['standard']
 Linter Variables:
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['standard']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
```

**Comment by w0rp** [comment]
Where have you installed `standard`?

**Comment by german1608** [comment]
in my `node_modules/` directory of my project.

**Comment by w0rp** [comment]
Does the executable exist in `node_modules/.bin/standard`, or in another location?

**Comment by german1608** [comment]
Yes. The executable is in the node_modules/.bin/ folder:

![image](https://user-images.githubusercontent.com/29154504/29640319-5ed67080-882c-11e7-9d5e-71863ccc23e6.png)

**Comment by w0rp** [comment]
Where is the file you are editing in the relation to your `node_modules` directory, and can you execute `standard` from node_modules?

**Comment by german1608** [comment]
The main file and the directory where are more files are both siblings of `node_modules`.
```
ls
node_modules/   test/(here are more js files)  index.js   package.json ....
```
You mean by executing `./node_modules/.bin/standard`? Yes

**Comment by w0rp** [comment]
After you pull from master, what do you get from `:ALEInfo`? Do you see any executable checks being done, or commands being run?

**Comment by german1608** [comment]
```
Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['standard']
 Linter Variables:
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['standard']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - failure) standard
(executable check - failure) standard
(executable check - failure) standard
(executable check - failure) standard
```

**Comment by german1608** [comment]
I just installed it globally and now works! Thanks for your help anyway!

**Comment by w0rp** [comment]
I'll see if I can figure out what the problem is here later and fix it. You shouldn't have to install `standard` globally.

**Comment by w0rp** [comment]
I tried creating a new directory and installing standard with `yarn add standard`, and it worked. Are you working on a React app by chance? I know that there are some scripts which install some files to different locations for React. Maybe opening `node_modules/.bin/standard` will provide some clues.

**Comment by german1608** [comment]
I'm not using React in that project. I installed `standard` via `npm`.

**Comment by german1608** [comment]
I just uninstalled it globally and doesn't work. I tried with another project that has `standard` installed but also doesn't works.

**Comment by w0rp** [comment]
Leave it installed globally so it works for you.

I recommend checking out the contents of `node_modules/.bin/standard`. That might give you some clues as to why the file isn't executable.

**Comment by german1608** [comment]
![image](https://user-images.githubusercontent.com/29154504/29742525-d5d6a406-8a4e-11e7-80f8-fb7b540e733f.png)
That file is a link and there are the content of that file

![image](https://user-images.githubusercontent.com/29154504/29742541-2a9f7ec2-8a4f-11e7-92ca-926e7f02f51f.png)
These are the contents of `option.js`

And [here](https://pastebin.com/1iiHehRh) is a pastebin of the source code of `node_modules/standard-engine/bin/cmd.js` (required at `standard` file)

**Comment by w0rp** [comment]
Pull ALE again. I just pushed a commit to prefer executing `node_modules/standard/bin/cmd.js` instead.

**Comment by german1608** [comment]
Same. I uninstalled standard globally and same happens

**Comment by german1608** [comment]
I'll try reinstalling it locally

**Comment by german1608** [comment]
THis is the output of `:ALEInfo`
```
Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['standard']
 Linter Variables:
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['standard']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - failure) standard
(executable check - failure) standard
(executable check - failure) standard
(executable check - failure) standard
```

**Comment by w0rp** [comment]
Hmm, I'm not sure. The executable checks there are still there for just `standard`. Could you create a project which repeats the bug and put that on GitHub somewhere? A zip file would do fine as well, etc. Let me know what environment you're running Vim, such as your Linux distribution, or other OS version. I'll take a look at that later and see if I can see anything wrong.

**Comment by german1608** [comment]
Ok. I'm using ubuntu 16.04. vim 8.0. I just create a new project and installed `standard` but nothing happens. It doesn't work. [Here](https://github.com/w0rp/ale/files/1254857/test.zip) is a zip file of the project that I created. I pulled ALE before testing everything.

**Comment by german1608** [comment]
What version of npm do you have? I'm using 3.10.1 . Maybe it's that idk

**Comment by w0rp** [comment]
I have `4.2.0`, but I use `yarn`, and whatever the latest version of that is.

**Comment by navdeepio** [comment]
same issue here, for me it does not work when I've installed standard globally.

Installing it in the project does the trick though..

**Comment by navdeepio** [comment]
Tried adding this, but to no avail

`let g:ale_javascript_standard_use_global = 1`

**Comment by juliankatz1991** [comment]
I'm also having trouble with `standard`, though not sure if this is the exact same problem...

My `ALEInfo` output:

```
 Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['standard']
 Linter Variables:
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['standard']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - success) /Users/A780976/personalDev/farm-web-app/node_modules/standard/bin/cmd.js
(started) ['/bin/zsh', '-c', '''/Users/A780976/personalDev/farm-web-app/node_modules/standard/bin/cmd.js'' --stdin ''/Users/A780976/personalDev/farm-web-app/src/App.js'' < ''/var/folders/qc/t8d0jpy13mq9j36cgl253vh80000gp/T/nvimukxGj8/3/App.js''']
(finished - exit code 127) ['/bin/zsh', '-c', '''/Users/A780976/personalDev/farm-web-app/node_modules/standard/bin/cmd.js'' --stdin ''/Users/A780976/personalDev/farm-web-app/src/App.js'' < ''/var/folders/qc/t8d0jpy13mq9j36cgl253vh80000gp/T/nvimukxGj8/4/App.js''']
<<<NO OUTPUT RETURNED>>>
(finished - exit code 127) ['/bin/zsh', '-c', '''/Users/A780976/personalDev/farm-web-app/node_modules/standard/bin/cmd.js'' --stdin ''/Users/A780976/personalDev/farm-web-app/src/App.js'' < ''/var/folders/qc/t8d0jpy13mq9j36cgl253vh80000gp/T/nvimukxGj8/5/App.js''']
<<<NO OUTPUT RETURNED>>>
```

The standard executable seems to be fine:
```
$ ls -al node_modules/.bin/standard
lrwxr-xr-x  1 A780976  staff    22B Nov 18 21:47 node_modules/.bin/standard -> ../standard/bin/cmd.js
```

For context, I also have `standard` installed globally:
```
$ which standard
/Users/A780976/.nvm/versions/node/v8.9.1/bin/standard
```
via `nvm`

I have tried adding the 
```
let g:ale_javascript_standard_use_global = 1
```
variable in my `~/.config/nvim/init.vim`, but it has had no effect.

Would appreciate any help!!  This is the last big piece of my `vim` --> `neovim` migration :)

**Comment by w0rp** [comment]
Try and use the local version if you can, so it will be updated along with your other packages. What's the problem?

**Comment by juliankatz1991** [comment]
@w0rp So there are 3 errors in the file:

```
$ standard src/App.js
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /Users/A780976/personalDev/farm-web-app/src/App.js:4:19: Extra semicolon.
  /Users/A780976/personalDev/farm-web-app/src/App.js:9:22: Unexpected usage of doublequote.
  /Users/A780976/personalDev/farm-web-app/src/App.js:10:27: Unexpected usage of doublequote.
```

These never show up in ALE

**Comment by juliankatz1991** [comment]
Problem solved!

Turns out it was a `PATH` problem after all.  For `zsh` users, note that:

`.zshrc` is run after `.zshenv`

Run your `nvm.sh` setup script at the bottom of `.zshrc`.

Sorry for the problem! Clearly had nothing to do with `ALE`.

**Comment by nightsdark** [comment]
I had a simular problem to juliankatz1991 

The debug output shows \<<NO OUTPUT RETURED\>>

###### I solved this: by fixing a missing comma in package.json

   The error was traced in my code from running
```{bash}
 standard src/app.js 
```
```{bash}
/home/chad/.nvm/versions/node/v8.9.1/lib/node_modules/standard/node_modules/pkg-conf/node_modules/parse-json/index.js:31
                throw jsonErr;
                ^
JSONError: Unexpected string in JSON at position 664 while parsing '{  "name": "application-name",  "versi' in package.json
    at module.exports (/home/chad/.nvm/versions/node/v8.9.1/lib/node_modules/standard/node_modules/pkg-conf/node_modules/parse-json/index.js:26:19)
    at parse (/home/chad/.nvm/versions/node/v8.9.1/lib/node_modules/standard/node_modules/pkg-conf/node_modules/load-json-file/index.js:8:29)
    at Function.module.exports.sync.fp [as sync] (/home/chad/.nvm/versions/node/v8.9.1/lib/node_modules/standard/node_modules/pkg-conf/node_modules/load-json-file/index.js:11:29)
    at Function.sync (/home/chad/.nvm/versions/node/v8.9.1/lib/node_modules/standard/node_modules/pkg-conf/index.js:52:27)
    at Linter.parseOpts (/home/chad/.nvm/versions/node/v8.9.1/lib/node_modules/standard/node_modules/standard-engine/index.js:140:15)
    at Linter.lintFiles (/home/chad/.nvm/versions/node/v8.9.1/lib/node_modules/standard/node_modules/standard-engine/index.js:94:15)
    at Object.Cli [as cli] (/home/chad/.nvm/versions/node/v8.9.1/lib/node_modules/standard/node_modules/standard-engine/bin/cmd.js:99:14)
    at Object.<anonymous> (/home/chad/.nvm/versions/node/v8.9.1/lib/node_modules/standard/bin/cmd.js:7:30)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
```
