### ISSUE TITLE
ALE produces lots of "npm-debug.log.*" files

### ISSUE THREAD

**Issue by dterei** [w0rp/ale#871]
Using ALE and it works great! However, it somehow causes the generation of "npm-debug.log.*" files. I can't tell what event causes their generation, they'll appear slowly overtime as I edit code, but I haven't found a way to trigger their generation myself.

I'm largely editing Go code and I tried disabling javascript linters / fixers in case this helps, but no change.

After say, 1 hour of editing code, I'll end up with about 10 files in the source code directory of the form "npm-debug.log.*".

If I disable ALE, then these files no longer get generated. Sorry can't be more specific, quite lost how and why this is happening.

**ALEInfo**

```
Current Filetype: go
Available Linters: ['go build', 'gofmt', 'golint', 'gometalinter', 'gosimple', 'go vet', 'staticcheck']
  Enabled Linters: ['gofmt', 'golint', 'go vet']
 Linter Variables:

 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'javascript': []}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': []}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(started) ['/usr/bin/zsh', '-c', 'gofmt -e ''/tmp/vTW5u0v/1/main.go''']
(started) ['/usr/bin/zsh', '-c', 'golint ''/tmp/vTW5u0v/2/main.go''']
(started) ['/usr/bin/zsh', '-c', 'go vet ''/tmp/vTW5u0v/3/main.go''']
(finished - exit code 0) ['/usr/bin/zsh', '-c', 'gofmt -e ''/tmp/vTW5u0v/4/main.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'golint ''/tmp/vTW5u0v/5/main.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'go vet ''/tmp/vTW5u0v/6/main.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'gofmt -e ''/tmp/vTW5u0v/14/main.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'golint ''/tmp/vTW5u0v/15/main.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'go vet ''/tmp/vTW5u0v/16/main.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'gofmt -e ''/tmp/vTW5u0v/17/main.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'golint ''/tmp/vTW5u0v/18/main.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'go vet ''/tmp/vTW5u0v/19/main.go''']

<<<NO OUTPUT RETURNED>>>
```

**npm-debug.log.18140963**:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/davidt/.nvm/versions/node/v7.4.0/bin/node',
1 verbose cli   '/home/davidt/.nvm/versions/node/v7.4.0/bin/npm',
1 verbose cli   'config',
1 verbose cli   '--loglevel=warn',
1 verbose cli   'get',
1 verbose cli   'prefix' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose exit [ 0, true ]
5 verbose stack Error: write EPIPE
5 verbose stack     at exports._errnoException (util.js:1022:11)
5 verbose stack     at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)
6 verbose cwd /home/davidt/Projects/spark/src/rubrik/cluster-poller
7 error Linux 4.12.8-2-ARCH
8 error argv "/home/davidt/.nvm/versions/node/v7.4.0/bin/node" "/home/davidt/.nvm/versions/node/v7.4.0/bin/npm" "config" "--loglevel=warn" "get" "prefix"
9 error node v7.4.0
10 error npm  v4.0.5
11 error code EPIPE
12 error errno EPIPE
13 error syscall write
14 error write EPIPE
15 error If you need help, you may report this error at:
15 error     <https://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]
```

**Comment by w0rp** [comment]
Look through every program you have which runs on Node, and diasble debugging for each program, one by one. ALE itself doesn't generate these files. One of the programs you are running might be generating these log files.

**Comment by w0rp** [comment]
I don't think there's anything that can be done about this in ALE.
